DROP SCHEMA PUBLIC CASCADE;

DROP SEQUENCE global_seq
IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ
  AS INTEGER
    START WITH 100000;

CREATE TABLE users
(
  id         INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  login      VARCHAR(255) NOT NULL,
  password   VARCHAR(255) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name  VARCHAR(255) NOT NULL,
  enabled    BOOLEAN   DEFAULT TRUE,
  registered TIMESTAMP DEFAULT now()
);
CREATE UNIQUE INDEX users_unique_email_idx
  ON users (login);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY ( user_id ) REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE TABLE restaurants
(
  id        INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name      VARCHAR(255) NOT NULL,
  imageLink VARCHAR(255) DEFAULT NULL,
  CONSTRAINT restaurants_unique_name_idx UNIQUE (name)
);

CREATE TABLE menus
(
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  restaurant_id INTEGER NOT NULL,
  dateOfMenu    TIMESTAMP DEFAULT now(),
  CONSTRAINT restaurant_id_created_idx UNIQUE (restaurant_id, dateOfMenu),
  FOREIGN KEY ( restaurant_id ) REFERENCES restaurants (id)
    ON DELETE CASCADE
);

CREATE TABLE dishes
(
  id        INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name      VARCHAR(255) NOT NULL,
  imageLink VARCHAR(255) NOT NULL,
  CONSTRAINT dishes_name_idx UNIQUE (name)
);

CREATE TABLE menus_dishes
(
  id      INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  dish_id INTEGER NOT NULL,
  menu_id INTEGER NOT NULL,
  price   DOUBLE  NOT NULL,
  CONSTRAINT dish_id_menu_id_idx UNIQUE (dish_id, menu_id),
  FOREIGN KEY ( dish_id ) REFERENCES dishes (id)
    ON DELETE CASCADE,
  FOREIGN KEY ( menu_id ) REFERENCES menus (id)
    ON DELETE CASCADE
);

CREATE TABLE votes
(
  id             INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  restaurant_id  INTEGER NOT NULL,
  user_id        INTEGER NOT NULL,
  vote_timestamp TIMESTAMP DEFAULT now(),
  CONSTRAINT votes_restaurant_id_user_id_vote_timestamp_idx UNIQUE (restaurant_id, user_id, vote_timestamp),
  FOREIGN KEY ( restaurant_id ) REFERENCES restaurants (id)
    ON DELETE CASCADE,
  FOREIGN KEY ( user_id ) REFERENCES users (id)
    ON DELETE CASCADE
);

